[package]
name = "K_Lang"
version = "0.1.0"
authors = ["KevinCybura <KevinCybura@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }
